### ISSUE TITLE
Add pull to refresh to issue list

### ISSUE THREAD

**Issue by chimon2000** [chimon2000/good_first_issue#8]
Currently, there is no way for a user to refresh the issue list.  They should be able to refresh the list by using "pull to refresh"

This feature should not reset the issue count used for querying. 

Seems pretty straightforward from [this article](https://codingwithjoe.com/flutter-implementing-pull-to-refresh/)

**Comment by hientranea** [comment]
Hi @chimon2000 , can I work on this issue?

**Comment by chimon2000** [comment]
@hientranea Sure!

**Comment by hientranea** [comment]
@chimon2000 , I've just created PR for this issue. Please take a look.
